// <auto-generated />
using System;
using APITemplate.Data.AuthModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APITemplate.Data.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20260423225919_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APITemplate.Data.AuthModels.ApiResource", b =>
                {
                    b.Property<int>("ApiResourcePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("api_resource_pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ApiResourcePk"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ApiResourcePk")
                        .HasName("api_resource_pkey");

                    b.HasIndex(new[] { "Audience" }, "ux_api_resource_audience")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "ux_api_resource_name")
                        .IsUnique();

                    b.ToTable("api_resource", (string)null);
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ApiScope", b =>
                {
                    b.Property<int>("ScopePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("scope_pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ScopePk"));

                    b.Property<int>("ApiResourcePk")
                        .HasColumnType("integer")
                        .HasColumnName("api_resource_pk");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ScopeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope_name");

                    b.HasKey("ScopePk")
                        .HasName("api_scope_pkey");

                    b.HasIndex(new[] { "ApiResourcePk" }, "ix_api_scope_api_resource_pk");

                    b.ToTable("api_scope", (string)null);
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.Client", b =>
                {
                    b.Property<int>("ClientPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ClientPk"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("ClientPk")
                        .HasName("client_pkey");

                    b.HasIndex(new[] { "ClientId" }, "ux_client_client_id")
                        .IsUnique();

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ClientScopeGrant", b =>
                {
                    b.Property<int>("GrantPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grant_pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("GrantPk"));

                    b.Property<int>("ClientPk")
                        .HasColumnType("integer")
                        .HasColumnName("client_pk");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("ScopePk")
                        .HasColumnType("integer")
                        .HasColumnName("scope_pk");

                    b.HasKey("GrantPk")
                        .HasName("client_scope_grant_pkey");

                    b.HasIndex("ScopePk");

                    b.HasIndex(new[] { "ClientPk", "ScopePk" }, "ux_client_scope_grant_client_scope")
                        .IsUnique();

                    b.ToTable("client_scope_grant", (string)null);
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ClientSecret", b =>
                {
                    b.Property<int>("ClientSecretPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_secret_pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ClientSecretPk"));

                    b.Property<int>("ClientPk")
                        .HasColumnType("integer")
                        .HasColumnName("client_pk");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("secret_hash");

                    b.HasKey("ClientSecretPk")
                        .HasName("client_secret_pkey");

                    b.HasIndex(new[] { "ClientPk" }, "ix_client_secret_client_pk");

                    b.ToTable("client_secret", (string)null);
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ApiScope", b =>
                {
                    b.HasOne("APITemplate.Data.AuthModels.ApiResource", "ApiResourcePkNavigation")
                        .WithMany("ApiScopes")
                        .HasForeignKey("ApiResourcePk")
                        .IsRequired()
                        .HasConstraintName("fk_api_scope_api_resource");

                    b.Navigation("ApiResourcePkNavigation");
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ClientScopeGrant", b =>
                {
                    b.HasOne("APITemplate.Data.AuthModels.Client", "ClientPkNavigation")
                        .WithMany("ClientScopeGrants")
                        .HasForeignKey("ClientPk")
                        .IsRequired()
                        .HasConstraintName("fk_client_scope_grant_client");

                    b.HasOne("APITemplate.Data.AuthModels.ApiScope", "ScopePkNavigation")
                        .WithMany("ClientScopeGrants")
                        .HasForeignKey("ScopePk")
                        .IsRequired()
                        .HasConstraintName("fk_client_scope_grant_scope");

                    b.Navigation("ClientPkNavigation");

                    b.Navigation("ScopePkNavigation");
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ClientSecret", b =>
                {
                    b.HasOne("APITemplate.Data.AuthModels.Client", "ClientPkNavigation")
                        .WithMany("ClientSecrets")
                        .HasForeignKey("ClientPk")
                        .IsRequired()
                        .HasConstraintName("fk_client_secret_client");

                    b.Navigation("ClientPkNavigation");
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ApiResource", b =>
                {
                    b.Navigation("ApiScopes");
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.ApiScope", b =>
                {
                    b.Navigation("ClientScopeGrants");
                });

            modelBuilder.Entity("APITemplate.Data.AuthModels.Client", b =>
                {
                    b.Navigation("ClientScopeGrants");

                    b.Navigation("ClientSecrets");
                });
#pragma warning restore 612, 618
        }
    }
}
